# Generated by Django 3.1.5 on 2021-03-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_image',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
