# Generated by Django 3.1.5 on 2021-03-17 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_product_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_image',
            name='image',
        ),
    ]
