# Generated by Django 3.1.5 on 2021-03-18 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_auto_20210318_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orders_detail',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.IntegerField(),
        ),
    ]
